package day7

val data = mapOf(
    "vibrant purple" to "3 shiny lavender bags, 1 mirrored gray bag, 4 muted bronze bags",
    "posh crimson" to "4 drab plum bags, 5 dotted purple bags, 3 vibrant lavender bags, 2 striped plum bags",
    "pale cyan" to "5 drab violet bags, 2 dotted crimson bags",
    "dim lime" to "1 muted purple bag, 2 striped silver bags",
    "clear aqua" to "2 plaid green bags",
    "bright teal" to "4 shiny crimson bags, 3 faded red bags, 2 posh lavender bags",
    "clear white" to "1 pale olive bag, 2 vibrant plum bags, 4 clear cyan bags",
    "dull plum" to "1 bright yellow bag, 5 bright tomato bags",
    "dark crimson" to "3 dotted gray bags",
    "shiny green" to "4 pale violet bags, 3 muted teal bags",
    "clear salmon" to "1 light yellow bag",
    "dull salmon" to "1 dim lavender bag, 3 faded teal bags, 4 dotted beige bags, 1 faded red bag",
    "pale black" to "4 drab maroon bags, 4 dotted orange bags, 1 shiny black bag, 4 mirrored yellow bags",
    "vibrant olive" to "5 clear chartreuse bags, 4 clear blue bags, 4 mirrored orange bags, 1 posh tomato bag",
    "shiny blue" to "3 light green bags, 5 dark chartreuse bags",
    "dark teal" to "1 posh maroon bag",
    "vibrant brown" to "no other bags",
    "striped crimson" to "2 shiny gold bags, 4 pale indigo bags, 4 light maroon bags",
    "bright fuchsia" to "1 posh purple bag, 4 clear gold bags, 5 dark teal bags, 2 plaid orange bags",
    "bright black" to "1 bright teal bag, 4 dull olive bags, 5 posh turquoise bags, 3 dotted teal bags",
    "striped beige" to "3 dark indigo bags, 1 drab aqua bag",
    "dim crimson" to "5 striped turquoise bags, 4 faded brown bags",
    "vibrant black" to "2 mirrored gray bags, 5 light maroon bags, 5 pale plum bags, 3 mirrored black bags",
    "muted chartreuse" to "4 dim indigo bags",
    "dotted bronze" to "3 clear aqua bags, 2 bright tan bags, 4 muted brown bags, 1 bright maroon bag",
    "posh cyan" to "1 vibrant black bag, 3 vibrant coral bags",
    "mirrored brown" to "5 pale gray bags, 4 dim beige bags",
    "vibrant indigo" to "5 mirrored maroon bags, 3 drab purple bags",
    "clear maroon" to "5 dotted teal bags, 4 wavy black bags",
    "faded silver" to "2 plaid red bags, 1 posh green bag, 3 vibrant magenta bags, 2 bright magenta bags",
    "light coral" to "5 dull turquoise bags",
    "wavy beige" to "2 shiny yellow bags, 1 shiny lavender bag, 3 plaid bronze bags",
    "faded fuchsia" to "5 light maroon bags, 2 mirrored cyan bags, 3 light aqua bags",
    "dark fuchsia" to "2 dotted blue bags, 5 muted olive bags, 5 posh coral bags, 4 clear salmon bags",
    "vibrant white" to "1 dim lavender bag",
    "bright plum" to "2 shiny tan bags",
    "wavy green" to "1 light beige bag, 5 mirrored blue bags, 1 pale turquoise bag",
    "posh magenta" to "4 dim violet bags, 3 clear aqua bags",
    "plaid coral" to "3 wavy salmon bags, 2 dark gold bags",
    "dull orange" to "1 dull green bag",
    "shiny aqua" to "1 plaid yellow bag, 3 shiny green bags, 5 vibrant bronze bags, 2 striped olive bags",
    "dotted teal" to "1 light gray bag, 1 dotted beige bag, 3 shiny gold bags, 3 faded tan bags",
    "dotted red" to "3 mirrored gray bags, 1 mirrored lime bag",
    "muted fuchsia" to "4 drab tan bags",
    "striped tomato" to "1 wavy silver bag, 3 bright blue bags, 5 drab silver bags, 5 dim orange bags",
    "vibrant coral" to "5 shiny plum bags, 5 pale aqua bags",
    "plaid gold" to "1 mirrored cyan bag, 2 dull lavender bags",
    "posh olive" to "1 shiny coral bag, 4 clear beige bags, 4 light bronze bags, 2 striped olive bags",
    "posh teal" to "1 drab yellow bag",
    "bright green" to "4 drab purple bags, 5 shiny yellow bags",
    "pale lavender" to "3 drab olive bags, 2 muted beige bags, 4 muted blue bags, 1 dim fuchsia bag",
    "faded green" to "1 dim turquoise bag, 5 drab cyan bags, 2 clear tomato bags, 2 light brown bags",
    "wavy blue" to "2 striped red bags, 5 dark gold bags, 5 clear white bags",
    "plaid olive" to "5 pale aqua bags",
    "muted purple" to "4 bright bronze bags",
    "vibrant turquoise" to "1 dark silver bag, 5 plaid teal bags, 5 posh turquoise bags",
    "striped chartreuse" to "5 muted bronze bags, 2 wavy salmon bags",
    "drab cyan" to "2 posh tomato bags, 1 wavy turquoise bag",
    "vibrant silver" to "3 light violet bags, 4 vibrant brown bags, 2 light beige bags, 5 dark indigo bags",
    "faded salmon" to "5 dim beige bags, 5 dotted beige bags",
    "light cyan" to "4 plaid beige bags, 5 vibrant black bags, 4 pale chartreuse bags, 4 plaid gray bags",
    "light aqua" to "5 faded red bags",
    "vibrant lavender" to "1 bright black bag, 5 plaid indigo bags",
    "drab salmon" to "1 dotted gray bag, 5 mirrored silver bags, 1 shiny bronze bag, 1 faded bronze bag",
    "striped coral" to "4 light silver bags",
    "vibrant gray" to "5 striped green bags, 2 light turquoise bags",
    "dark aqua" to "3 dark teal bags, 5 clear bronze bags, 5 dotted tan bags",
    "dark olive" to "5 light gold bags, 3 dark green bags",
    "clear lime" to "5 dull red bags, 3 mirrored salmon bags, 1 bright crimson bag, 4 vibrant black bags",
    "dull gold" to "1 dark violet bag, 1 dim chartreuse bag, 1 vibrant lavender bag, 2 clear red bags",
    "dim black" to "5 dull black bags, 3 faded silver bags, 5 pale red bags",
    "clear yellow" to "2 clear beige bags, 2 shiny fuchsia bags, 1 plaid coral bag",
    "mirrored gold" to "5 dotted plum bags",
    "dotted maroon" to "3 dotted purple bags",
    "dim bronze" to "2 wavy magenta bags, 2 drab red bags",
    "wavy white" to "3 dull lime bags, 4 drab tan bags",
    "vibrant aqua" to "1 drab tan bag, 3 light crimson bags",
    "mirrored cyan" to "2 dull olive bags",
    "faded crimson" to "3 bright fuchsia bags, 5 dotted chartreuse bags, 4 striped plum bags",
    "faded purple" to "5 faded lime bags, 3 drab lavender bags",
    "striped black" to "1 vibrant tan bag, 1 drab maroon bag",
    "striped magenta" to "2 drab lavender bags, 2 shiny bronze bags, 2 posh salmon bags",
    "shiny olive" to "1 posh violet bag, 4 dotted orange bags, 1 drab maroon bag, 5 drab lavender bags",
    "dull tan" to "1 wavy violet bag, 2 plaid plum bags, 4 bright lavender bags",
    "pale indigo" to "1 striped chartreuse bag, 4 bright magenta bags, 5 wavy salmon bags",
    "dotted magenta" to "4 posh red bags, 2 light lime bags, 2 dull fuchsia bags",
    "vibrant blue" to "2 drab brown bags, 3 muted orange bags",
    "clear turquoise" to "2 muted crimson bags, 2 drab bronze bags, 4 drab white bags, 1 clear white bag",
    "drab bronze" to "1 faded olive bag, 4 dim indigo bags, 3 pale black bags",
    "shiny white" to "5 pale plum bags, 1 mirrored aqua bag",
    "striped teal" to "1 dull lime bag",
    "light lavender" to "2 mirrored brown bags, 3 bright orange bags",
    "light magenta" to "3 striped silver bags, 1 drab yellow bag, 4 bright orange bags, 5 dotted lavender bags",
    "mirrored salmon" to "2 bright magenta bags, 3 drab aqua bags, 3 shiny gold bags",
    "muted lavender" to "5 wavy chartreuse bags, 1 dark coral bag, 2 plaid gray bags",
    "muted yellow" to "1 dim lavender bag, 5 faded gold bags, 3 clear beige bags",
    "vibrant maroon" to "1 faded salmon bag, 2 vibrant tan bags, 1 posh fuchsia bag, 5 plaid gold bags",
    "bright lavender" to "2 pale gray bags",
    "plaid salmon" to "5 dull fuchsia bags, 4 faded gold bags, 2 dark teal bags, 1 bright teal bag",
    "dark turquoise" to "1 dull fuchsia bag, 3 dull tomato bags, 1 striped cyan bag",
    "dark indigo" to "1 dotted red bag",
    "light green" to "4 vibrant bronze bags, 1 wavy black bag, 1 dark black bag",
    "drab magenta" to "5 mirrored beige bags, 1 faded brown bag",
    "clear coral" to "5 posh green bags, 5 dull yellow bags, 2 dim salmon bags",
    "light red" to "1 light silver bag, 1 mirrored lime bag",
    "muted beige" to "2 drab yellow bags, 4 light maroon bags, 2 shiny yellow bags",
    "pale blue" to "5 mirrored crimson bags, 1 drab salmon bag, 2 posh lime bags",
    "drab crimson" to "2 light salmon bags, 5 pale gray bags, 2 wavy beige bags",
    "faded maroon" to "5 mirrored gold bags",
    "bright indigo" to "5 pale gray bags",
    "dull teal" to "3 faded silver bags, 1 vibrant lime bag, 1 mirrored crimson bag",
    "shiny salmon" to "3 bright magenta bags, 4 dotted blue bags, 1 dotted maroon bag, 3 bright beige bags",
    "mirrored beige" to "1 vibrant magenta bag, 5 light silver bags, 5 shiny lavender bags",
    "pale tan" to "4 striped magenta bags, 1 clear cyan bag, 1 clear beige bag, 1 mirrored purple bag",
    "drab tan" to "5 mirrored maroon bags",
    "dark yellow" to "2 dull olive bags, 4 dull teal bags, 4 light yellow bags, 1 faded fuchsia bag",
    "drab green" to "1 clear magenta bag",
    "pale turquoise" to "2 drab chartreuse bags",
    "plaid silver" to "3 dotted beige bags, 2 plaid orange bags",
    "vibrant red" to "5 muted magenta bags, 4 drab white bags, 1 drab aqua bag",
    "muted maroon" to "2 shiny coral bags",
    "mirrored purple" to "4 mirrored aqua bags",
    "muted white" to "2 plaid green bags, 2 posh green bags, 5 faded gray bags",
    "bright chartreuse" to "2 bright lavender bags, 1 muted tan bag",
    "vibrant orange" to "4 muted bronze bags, 5 vibrant magenta bags",
    "clear chartreuse" to "2 plaid red bags, 2 striped teal bags, 5 dotted fuchsia bags",
    "clear gray" to "1 dull beige bag, 3 light aqua bags",
    "striped indigo" to "2 faded chartreuse bags, 4 dull white bags, 5 mirrored maroon bags, 1 plaid coral bag",
    "posh green" to "1 bright tan bag",
    "dark salmon" to "5 wavy yellow bags",
    "muted tomato" to "3 muted beige bags, 2 faded gray bags, 2 clear gold bags",
    "posh silver" to "2 dotted beige bags, 2 pale fuchsia bags, 1 dark brown bag",
    "mirrored white" to "5 dim white bags, 3 light aqua bags, 2 faded gray bags, 3 shiny gold bags",
    "drab chartreuse" to "5 mirrored plum bags, 2 dim aqua bags, 1 vibrant brown bag, 5 vibrant orange bags",
    "light blue" to "3 dim chartreuse bags, 1 bright green bag, 3 clear chartreuse bags",
    "posh white" to "1 dull brown bag, 3 bright magenta bags",
    "dotted violet" to "3 plaid gray bags, 5 pale white bags, 5 wavy blue bags, 1 mirrored magenta bag",
    "drab plum" to "1 dull salmon bag, 2 muted magenta bags",
    "plaid violet" to "3 bright olive bags",
    "wavy crimson" to "2 bright purple bags, 3 shiny yellow bags, 3 posh bronze bags",
    "dull yellow" to "1 plaid red bag, 1 plaid maroon bag",
    "dull magenta" to "4 dark olive bags, 3 faded olive bags",
    "faded brown" to "4 light yellow bags, 3 drab red bags",
    "bright crimson" to "4 posh lime bags, 1 mirrored gray bag, 5 pale indigo bags",
    "bright lime" to "3 faded violet bags",
    "dotted white" to "2 pale fuchsia bags, 4 light red bags, 3 dull gold bags, 1 wavy salmon bag",
    "dull cyan" to "2 dark indigo bags, 5 muted black bags, 4 wavy aqua bags",
    "light plum" to "4 wavy beige bags, 2 clear crimson bags, 5 striped beige bags",
    "wavy chartreuse" to "1 dark indigo bag",
    "clear cyan" to "1 mirrored lime bag, 4 light silver bags",
    "striped salmon" to "3 dotted silver bags, 1 shiny turquoise bag, 3 mirrored tan bags",
    "bright cyan" to "1 wavy tomato bag, 4 dotted yellow bags, 2 pale tan bags",
    "muted red" to "2 vibrant chartreuse bags, 1 dim indigo bag, 5 muted aqua bags",
    "mirrored plum" to "1 light black bag, 3 vibrant brown bags",
    "mirrored lime" to "5 bright violet bags, 4 light maroon bags, 1 dotted beige bag, 2 plaid maroon bags",
    "dotted chartreuse" to "5 light black bags, 3 shiny turquoise bags, 5 drab lavender bags, 3 shiny silver bags",
    "plaid brown" to "2 drab gold bags, 5 clear cyan bags, 2 drab gray bags, 2 vibrant magenta bags",
    "clear olive" to "5 shiny cyan bags, 1 dark teal bag, 3 striped bronze bags, 2 striped olive bags",
    "light beige" to "5 pale plum bags",
    "dark cyan" to "5 posh tomato bags, 3 clear magenta bags, 2 shiny olive bags",
    "dark maroon" to "1 shiny turquoise bag, 2 dotted brown bags, 3 dark lime bags",
    "vibrant teal" to "2 pale purple bags",
    "dotted turquoise" to "5 vibrant magenta bags, 3 dark chartreuse bags",
    "dark red" to "2 striped chartreuse bags",
    "pale purple" to "4 drab gold bags, 1 drab violet bag, 3 muted black bags",
    "vibrant fuchsia" to "2 shiny purple bags",
    "dotted gold" to "2 shiny gold bags, 2 plaid coral bags",
    "striped aqua" to "3 dark chartreuse bags",
    "light orange" to "1 plaid red bag, 3 wavy salmon bags, 4 dotted indigo bags",
    "dotted lavender" to "4 dotted tomato bags, 3 plaid cyan bags",
    "light bronze" to "3 drab purple bags, 4 dotted crimson bags, 1 posh bronze bag",
    "dim tomato" to "4 dotted tan bags, 2 vibrant brown bags, 5 vibrant orange bags, 2 dotted silver bags",
    "striped plum" to "4 wavy indigo bags, 5 dim indigo bags, 3 vibrant green bags",
    "clear beige" to "3 muted bronze bags",
    "shiny coral" to "2 posh silver bags",
    "dull violet" to "5 bright teal bags, 3 plaid violet bags, 3 drab turquoise bags, 3 dull maroon bags",
    "posh yellow" to "2 light maroon bags, 3 light fuchsia bags, 1 shiny indigo bag",
    "dark tan" to "3 plaid yellow bags, 2 striped salmon bags",
    "shiny fuchsia" to "2 faded red bags, 3 dim violet bags, 4 wavy crimson bags",
    "clear purple" to "3 shiny chartreuse bags",
    "dim turquoise" to "5 vibrant magenta bags, 2 striped tomato bags",
    "light turquoise" to "5 wavy crimson bags, 3 dim beige bags, 2 bright teal bags, 3 posh maroon bags",
    "mirrored magenta" to "1 shiny turquoise bag",
    "clear blue" to "3 dark black bags, 4 faded fuchsia bags",
    "muted gray" to "1 light chartreuse bag",
    "wavy maroon" to "4 bright magenta bags, 1 vibrant orange bag",
    "shiny silver" to "4 dull white bags, 5 striped aqua bags",
    "clear silver" to "3 vibrant coral bags, 4 light gray bags, 4 shiny maroon bags",
    "wavy magenta" to "5 clear red bags, 4 shiny yellow bags, 2 dark green bags, 1 shiny cyan bag",
    "dull green" to "2 vibrant salmon bags",
    "wavy red" to "4 bright indigo bags",
    "wavy turquoise" to "4 clear gray bags, 4 dark chartreuse bags, 4 dark lavender bags",
    "faded tomato" to "5 wavy salmon bags, 1 muted salmon bag, 2 muted black bags",
    "dark orange" to "3 dim red bags, 3 dim silver bags, 2 muted beige bags, 5 bright silver bags",
    "shiny tomato" to "3 bright green bags, 3 dark blue bags, 2 wavy chartreuse bags",
    "clear fuchsia" to "2 dotted tan bags, 4 posh plum bags, 3 light green bags, 4 drab crimson bags",
    "pale tomato" to "3 faded bronze bags",
    "dull coral" to "5 plaid magenta bags, 1 mirrored cyan bag, 1 dark black bag",
    "pale gray" to "1 bright tan bag",
    "drab olive" to "2 posh blue bags, 1 dim salmon bag, 3 posh orange bags, 5 posh maroon bags",
    "plaid beige" to "3 muted olive bags, 2 drab fuchsia bags",
    "dotted coral" to "2 dark magenta bags",
    "bright magenta" to "no other bags",
    "striped violet" to "1 plaid gray bag, 5 dull white bags, 3 dark indigo bags, 1 shiny orange bag",
    "plaid tomato" to "1 dotted orange bag, 5 bright silver bags",
    "wavy silver" to "no other bags",
    "wavy bronze" to "5 plaid beige bags, 5 dark coral bags, 5 vibrant orange bags",
    "clear black" to "3 wavy beige bags",
    "drab teal" to "5 dull gray bags, 1 light yellow bag, 3 drab indigo bags, 1 bright maroon bag",
    "dim lavender" to "4 shiny lavender bags",
    "pale olive" to "4 wavy olive bags, 4 faded olive bags",
    "shiny turquoise" to "5 clear magenta bags, 1 mirrored aqua bag, 2 light lime bags, 2 dark indigo bags",
    "clear brown" to "1 dotted fuchsia bag, 4 clear white bags",
    "pale red" to "4 clear beige bags",
    "bright maroon" to "4 clear black bags, 2 vibrant white bags",
    "pale teal" to "3 pale silver bags, 2 wavy tomato bags",
    "plaid orange" to "5 shiny magenta bags",
    "posh plum" to "2 clear beige bags, 5 faded silver bags, 5 drab beige bags, 4 dim crimson bags",
    "pale maroon" to "1 posh maroon bag, 4 wavy magenta bags",
    "shiny black" to "1 dotted tomato bag, 1 mirrored silver bag, 5 plaid maroon bags, 5 clear salmon bags",
    "shiny lavender" to "5 muted bronze bags",
    "wavy violet" to "2 dotted tomato bags, 5 bright black bags, 4 clear cyan bags",
    "dotted tan" to "4 plaid teal bags",
    "drab tomato" to "5 dark black bags",
    "dull olive" to "1 clear salmon bag",
    "faded orange" to "2 light maroon bags, 3 posh lime bags, 4 dotted tan bags",
    "plaid purple" to "5 drab aqua bags, 3 clear plum bags, 2 pale purple bags",
    "wavy fuchsia" to "3 faded orange bags, 1 muted purple bag",
    "pale white" to "5 dark indigo bags, 1 pale tan bag",
    "bright olive" to "1 dull lime bag, 3 light fuchsia bags",
    "drab black" to "4 muted violet bags, 2 vibrant violet bags",
    "drab lime" to "5 dark brown bags, 5 striped indigo bags",
    "striped green" to "5 vibrant green bags, 3 striped silver bags, 2 dull turquoise bags, 4 drab indigo bags",
    "wavy olive" to "3 mirrored gray bags, 1 light lime bag, 2 bright indigo bags",
    "posh indigo" to "2 dotted fuchsia bags, 3 dotted purple bags, 2 wavy brown bags, 2 dotted blue bags",
    "clear crimson" to "5 drab gray bags, 2 plaid beige bags, 4 dark gold bags, 2 pale chartreuse bags",
    "pale lime" to "1 dotted plum bag, 2 vibrant maroon bags",
    "pale gold" to "4 posh tomato bags",
    "posh tomato" to "4 mirrored lime bags",
    "muted indigo" to "5 wavy fuchsia bags, 3 clear orange bags, 3 shiny green bags",
    "clear green" to "3 drab salmon bags, 4 pale turquoise bags",
    "mirrored yellow" to "5 dim red bags",
    "pale bronze" to "1 dotted chartreuse bag, 1 drab teal bag, 4 shiny cyan bags, 5 faded brown bags",
    "shiny maroon" to "2 wavy turquoise bags, 5 light turquoise bags, 5 wavy cyan bags",
    "dark magenta" to "4 mirrored lime bags, 3 drab aqua bags, 4 bright blue bags, 2 posh silver bags",
    "drab gold" to "2 light gray bags, 3 bright magenta bags, 2 vibrant magenta bags, 4 light lime bags",
    "drab brown" to "2 wavy salmon bags, 5 posh plum bags, 4 shiny orange bags",
    "dull gray" to "2 dim violet bags",
    "muted magenta" to "5 posh lavender bags, 2 dotted orange bags, 4 pale turquoise bags",
    "vibrant bronze" to "5 dim blue bags, 3 mirrored silver bags",
    "pale crimson" to "2 dark coral bags",
    "dotted cyan" to "2 clear salmon bags, 4 dark white bags",
    "light white" to "5 clear silver bags, 4 clear olive bags",
    "dim coral" to "3 drab silver bags, 5 shiny teal bags, 4 faded bronze bags, 4 muted plum bags",
    "dotted beige" to "1 light yellow bag, 4 light lime bags",
    "faded turquoise" to "4 dotted tomato bags, 3 pale magenta bags, 2 dim brown bags",
    "shiny brown" to "5 faded red bags",
    "striped yellow" to "3 mirrored crimson bags, 4 dark magenta bags, 3 pale crimson bags, 2 mirrored black bags",
    "shiny magenta" to "1 vibrant tomato bag, 3 mirrored lavender bags",
    "clear indigo" to "4 muted tomato bags, 3 posh red bags, 5 pale turquoise bags, 3 dim olive bags",
    "striped silver" to "4 drab maroon bags, 2 drab chartreuse bags, 2 dotted gray bags",
    "mirrored black" to "1 wavy beige bag, 1 dim silver bag",
    "faded cyan" to "3 dim crimson bags, 3 drab aqua bags",
    "posh lavender" to "2 light gray bags, 1 dim orange bag",
    "dim violet" to "2 posh maroon bags, 4 clear salmon bags",
    "plaid tan" to "5 shiny indigo bags, 1 shiny fuchsia bag",
    "posh maroon" to "5 dark magenta bags, 1 drab silver bag, 5 drab red bags",
    "striped turquoise" to "1 dull lime bag",
    "wavy tomato" to "3 dotted gray bags, 5 dull blue bags, 3 dotted purple bags",
    "drab fuchsia" to "5 drab red bags, 2 mirrored lime bags",
    "dotted green" to "5 posh turquoise bags",
    "pale chartreuse" to "1 striped beige bag, 5 dark chartreuse bags",
    "plaid cyan" to "3 drab gold bags, 1 light gray bag, 2 bright violet bags, 3 dark chartreuse bags",
    "dull blue" to "4 dotted yellow bags",
    "vibrant crimson" to "1 dotted beige bag",
    "light crimson" to "2 light black bags, 2 dotted beige bags",
    "posh turquoise" to "1 posh lavender bag, 4 vibrant orange bags, 4 shiny lavender bags",
    "dull beige" to "5 dull salmon bags",
    "shiny orange" to "5 drab gray bags, 1 plaid chartreuse bag, 5 dim crimson bags",
    "muted crimson" to "3 light cyan bags, 3 dull fuchsia bags, 2 bright red bags",
    "shiny gray" to "2 bright fuchsia bags, 5 vibrant maroon bags, 1 bright teal bag, 3 striped magenta bags",
    "bright brown" to "3 mirrored violet bags, 1 light aqua bag, 5 bright maroon bags",
    "faded teal" to "5 faded gray bags, 5 pale indigo bags, 5 plaid cyan bags",
    "faded violet" to "1 shiny fuchsia bag, 5 faded gray bags",
    "striped purple" to "2 wavy olive bags",
    "muted tan" to "1 clear red bag, 1 shiny crimson bag, 3 faded violet bags",
    "light chartreuse" to "5 faded turquoise bags",
    "mirrored bronze" to "4 wavy indigo bags",
    "plaid turquoise" to "5 pale aqua bags, 4 faded indigo bags",
    "drab aqua" to "1 light silver bag, 2 plaid bronze bags, 2 light black bags, 3 muted bronze bags",
    "posh red" to "5 faded aqua bags, 2 posh coral bags, 5 light lime bags, 3 faded gray bags",
    "bright aqua" to "5 faded orange bags, 2 bright silver bags, 1 posh fuchsia bag, 3 pale blue bags",
    "faded yellow" to "1 mirrored olive bag",
    "faded red" to "4 drab gold bags, 5 shiny turquoise bags",
    "wavy gray" to "1 dull salmon bag, 5 posh brown bags, 1 drab bronze bag",
    "striped fuchsia" to "3 faded tan bags, 5 posh turquoise bags, 2 dotted turquoise bags",
    "vibrant chartreuse" to "2 posh lavender bags, 1 plaid cyan bag, 3 muted brown bags",
    "faded chartreuse" to "4 drab gold bags, 3 faded gray bags",
    "dim chartreuse" to "3 dark maroon bags, 5 dim brown bags",
    "clear plum" to "2 dotted indigo bags, 5 dark white bags, 3 plaid indigo bags, 5 bright beige bags",
    "faded gold" to "4 dim beige bags, 3 light maroon bags, 4 vibrant brown bags, 3 muted olive bags",
    "dull fuchsia" to "5 dark white bags, 3 pale magenta bags, 1 bright blue bag, 3 drab salmon bags",
    "bright yellow" to "1 clear indigo bag, 5 dark white bags, 4 shiny indigo bags, 5 light orange bags",
    "faded aqua" to "3 drab red bags, 1 muted olive bag, 3 vibrant green bags",
    "shiny red" to "4 faded chartreuse bags, 1 plaid salmon bag, 5 clear crimson bags",
    "vibrant salmon" to "2 drab magenta bags",
    "vibrant plum" to "5 drab maroon bags, 3 plaid coral bags",
    "dull black" to "3 posh indigo bags, 4 light gray bags, 3 wavy salmon bags",
    "muted black" to "1 faded salmon bag, 4 dark blue bags",
    "dim cyan" to "1 posh salmon bag, 5 bright teal bags, 3 shiny olive bags",
    "posh blue" to "3 bright magenta bags, 4 light black bags, 2 vibrant orange bags",
    "light silver" to "2 shiny yellow bags",
    "drab coral" to "1 shiny chartreuse bag, 1 pale blue bag",
    "drab blue" to "1 bright lavender bag, 3 vibrant violet bags, 5 shiny yellow bags",
    "bright bronze" to "5 posh tomato bags, 5 plaid beige bags",
    "faded gray" to "1 vibrant brown bag, 3 posh lavender bags",
    "dark plum" to "3 dull bronze bags, 3 light coral bags",
    "light yellow" to "3 drab silver bags",
    "dim aqua" to "4 wavy beige bags, 5 light maroon bags",
    "dim orange" to "no other bags",
    "light olive" to "5 pale olive bags, 5 pale violet bags",
    "shiny indigo" to "4 plaid brown bags, 1 vibrant teal bag, 4 light black bags, 3 faded bronze bags",
    "light teal" to "5 dull cyan bags, 2 dim salmon bags",
    "dotted aqua" to "4 bright orange bags, 3 drab fuchsia bags, 3 dotted gray bags",
    "pale beige" to "3 wavy maroon bags",
    "posh lime" to "3 striped chartreuse bags, 4 drab gold bags, 3 light gray bags, 3 dim lavender bags",
    "mirrored silver" to "1 wavy salmon bag, 2 drab yellow bags, 2 dotted gray bags",
    "muted bronze" to "5 vibrant magenta bags, 4 light gray bags, 4 light lime bags",
    "bright violet" to "no other bags",
    "dotted fuchsia" to "1 dark indigo bag, 4 vibrant brown bags, 4 plaid olive bags, 5 muted olive bags",
    "posh tan" to "4 plaid beige bags, 4 dark indigo bags",
    "faded tan" to "4 bright tan bags, 4 mirrored plum bags, 5 striped tomato bags",
    "plaid fuchsia" to "1 wavy purple bag, 4 shiny teal bags, 3 shiny plum bags, 2 wavy white bags",
    "pale silver" to "3 plaid green bags, 3 drab chartreuse bags, 4 posh bronze bags",
    "plaid yellow" to "1 pale aqua bag, 2 drab chartreuse bags",
    "dark gold" to "3 wavy salmon bags",
    "mirrored tan" to "3 bright violet bags",
    "dotted crimson" to "3 dark magenta bags, 1 posh tomato bag",
    "bright beige" to "2 dark indigo bags, 5 dotted beige bags, 1 drab beige bag, 3 striped aqua bags",
    "plaid teal" to "1 dotted gold bag, 1 posh bronze bag",
    "vibrant magenta" to "no other bags",
    "clear tomato" to "5 pale indigo bags",
    "light violet" to "5 drab indigo bags, 1 pale violet bag, 5 drab purple bags, 2 vibrant tomato bags",
    "pale salmon" to "2 posh plum bags",
    "plaid gray" to "1 vibrant gray bag, 1 bright gold bag",
    "muted blue" to "1 shiny white bag, 4 pale teal bags, 4 dim crimson bags, 4 vibrant chartreuse bags",
    "muted aqua" to "5 wavy teal bags",
    "dim teal" to "4 plaid blue bags",
    "dim olive" to "4 dim silver bags, 1 faded brown bag",
    "posh coral" to "3 striped blue bags, 2 plaid olive bags, 3 plaid teal bags, 3 clear beige bags",
    "wavy lime" to "4 dull green bags, 1 posh maroon bag, 5 dotted lavender bags",
    "dark chartreuse" to "no other bags",
    "dotted yellow" to "5 bright magenta bags",
    "light fuchsia" to "1 plaid coral bag, 1 posh silver bag, 3 light orange bags",
    "dark purple" to "2 plaid bronze bags, 3 posh chartreuse bags, 1 light magenta bag",
    "striped tan" to "1 clear black bag, 1 posh blue bag, 4 faded salmon bags",
    "vibrant tan" to "1 pale red bag, 2 dull lime bags, 4 posh plum bags",
    "bright turquoise" to "4 drab aqua bags, 5 dull blue bags",
    "dull purple" to "1 striped fuchsia bag, 3 dark lavender bags",
    "light purple" to "3 bright blue bags, 5 mirrored beige bags, 2 muted beige bags",
    "plaid aqua" to "4 dotted indigo bags, 1 muted aqua bag",
    "shiny tan" to "3 pale magenta bags, 5 drab salmon bags, 2 dotted gold bags",
    "light brown" to "5 posh tomato bags, 1 light gray bag, 1 bright gold bag, 4 posh violet bags",
    "posh bronze" to "2 light black bags, 5 dim lavender bags",
    "dim red" to "no other bags",
    "pale yellow" to "3 bright tan bags, 3 plaid magenta bags",
    "dim salmon" to "4 dark white bags, 5 dotted brown bags, 1 striped aqua bag",
    "muted green" to "4 dim brown bags, 3 posh tan bags, 4 shiny olive bags, 4 clear fuchsia bags",
    "drab maroon" to "4 dull olive bags, 2 dotted black bags",
    "dotted black" to "2 dotted fuchsia bags, 3 dim aqua bags, 4 light orange bags, 5 light red bags",
    "striped lime" to "1 clear crimson bag",
    "dim gray" to "4 striped lavender bags, 1 wavy salmon bag, 3 posh violet bags, 3 dotted brown bags",
    "drab red" to "2 dim brown bags, 4 light lime bags",
    "muted olive" to "1 dark coral bag, 2 wavy silver bags, 5 drab silver bags, 5 pale fuchsia bags",
    "shiny crimson" to "5 light crimson bags, 2 clear magenta bags",
    "vibrant green" to "4 light orange bags",
    "wavy purple" to "5 dull brown bags",
    "mirrored indigo" to "3 clear bronze bags, 1 pale tan bag, 1 faded tomato bag",
    "dull white" to "3 dim beige bags, 2 light yellow bags, 2 dark indigo bags, 2 muted bronze bags",
    "bright tan" to "2 posh blue bags, 3 striped chartreuse bags",
    "mirrored olive" to "1 wavy maroon bag, 5 wavy silver bags, 5 shiny beige bags",
    "faded white" to "4 bright bronze bags, 1 plaid brown bag, 5 vibrant yellow bags, 2 drab indigo bags",
    "muted teal" to "2 striped crimson bags, 1 dim orange bag, 5 posh green bags",
    "faded coral" to "1 dim beige bag, 1 striped brown bag, 4 pale indigo bags, 1 posh fuchsia bag",
    "dim green" to "3 dark maroon bags, 4 striped chartreuse bags, 1 wavy purple bag",
    "wavy gold" to "3 clear aqua bags, 2 dim orange bags",
    "dotted purple" to "4 dotted indigo bags, 4 drab aqua bags, 2 dark coral bags, 3 muted beige bags",
    "dark beige" to "5 shiny fuchsia bags",
    "posh fuchsia" to "3 vibrant white bags",
    "mirrored maroon" to "3 dull white bags, 2 plaid gold bags, 4 plaid maroon bags, 2 bright crimson bags",
    "dim tan" to "1 dark white bag, 5 posh black bags, 3 plaid brown bags, 1 posh bronze bag",
    "posh purple" to "5 clear tomato bags",
    "dark tomato" to "1 posh lime bag",
    "dim gold" to "1 posh salmon bag, 5 dark red bags, 4 dark black bags, 2 faded orange bags",
    "plaid white" to "2 clear olive bags, 2 mirrored cyan bags, 3 muted white bags",
    "dull brown" to "5 plaid tomato bags, 2 dotted black bags",
    "light gold" to "3 plaid gold bags, 4 posh salmon bags, 2 dotted blue bags, 5 dull gray bags",
    "dark silver" to "2 light gray bags, 3 dotted fuchsia bags, 2 light red bags",
    "plaid green" to "4 light maroon bags, 1 striped tomato bag, 4 drab beige bags",
    "dull turquoise" to "2 light maroon bags, 3 posh silver bags, 5 dim lavender bags, 5 vibrant orange bags",
    "dark violet" to "3 wavy maroon bags, 1 clear salmon bag, 5 light yellow bags",
    "wavy brown" to "3 dim white bags",
    "faded magenta" to "3 dark silver bags, 4 vibrant purple bags, 1 dark white bag",
    "muted cyan" to "5 shiny beige bags, 3 muted white bags",
    "mirrored chartreuse" to "3 mirrored maroon bags, 2 faded indigo bags, 1 pale red bag",
    "mirrored turquoise" to "1 drab gold bag",
    "shiny purple" to "3 faded yellow bags, 2 pale aqua bags, 5 vibrant red bags",
    "faded lavender" to "2 dim gray bags, 3 dim blue bags, 4 dark black bags",
    "dotted blue" to "2 posh lime bags, 1 dotted beige bag, 4 mirrored aqua bags",
    "wavy cyan" to "3 dotted turquoise bags, 2 dark lime bags, 4 dotted crimson bags, 1 dotted lime bag",
    "faded lime" to "1 faded bronze bag, 5 dotted purple bags, 4 light orange bags",
    "striped red" to "1 shiny teal bag",
    "light indigo" to "5 shiny olive bags, 4 dim magenta bags, 5 plaid magenta bags, 5 dark violet bags",
    "wavy yellow" to "3 bright aqua bags, 1 dull blue bag, 1 bright olive bag",
    "posh beige" to "2 posh orange bags, 3 dotted olive bags, 3 dull yellow bags, 1 wavy white bag",
    "muted turquoise" to "4 bright silver bags, 4 wavy silver bags",
    "drab purple" to "5 bright tan bags",
    "vibrant lime" to "3 plaid magenta bags, 2 vibrant white bags, 2 dark gold bags, 1 light green bag",
    "clear violet" to "3 muted red bags, 4 posh yellow bags, 2 pale indigo bags",
    "pale fuchsia" to "2 wavy beige bags, 2 plaid bronze bags, 2 wavy silver bags",
    "plaid black" to "4 pale olive bags, 3 pale fuchsia bags",
    "vibrant violet" to "1 plaid red bag, 5 drab red bags, 5 pale gray bags",
    "mirrored crimson" to "1 dotted fuchsia bag",
    "posh aqua" to "3 plaid teal bags",
    "shiny teal" to "4 dotted black bags",
    "drab orange" to "5 dotted teal bags, 4 drab white bags, 3 pale olive bags",
    "posh chartreuse" to "3 drab gray bags",
    "plaid indigo" to "2 striped tomato bags",
    "plaid lime" to "5 drab purple bags",
    "dull tomato" to "2 wavy turquoise bags",
    "wavy black" to "5 mirrored blue bags, 5 striped tan bags",
    "posh brown" to "3 wavy purple bags, 1 mirrored violet bag",
    "dim purple" to "5 clear gray bags, 1 plaid green bag, 3 light green bags",
    "dotted indigo" to "4 drab silver bags",
    "striped cyan" to "5 light orange bags, 1 dim chartreuse bag, 1 bright blue bag, 5 dim coral bags",
    "striped brown" to "1 light turquoise bag, 1 mirrored coral bag",
    "wavy salmon" to "2 vibrant orange bags, 2 drab silver bags, 3 bright blue bags, 1 vibrant brown bag",
    "drab lavender" to "5 dotted fuchsia bags, 1 plaid green bag, 4 posh salmon bags",
    "drab silver" to "4 muted bronze bags, 2 drab gold bags",
    "plaid maroon" to "1 vibrant brown bag, 4 shiny yellow bags, 3 bright blue bags, 5 drab gold bags",
    "vibrant beige" to "2 drab indigo bags, 2 dim aqua bags",
    "mirrored green" to "1 dim coral bag, 5 muted orange bags, 1 dotted purple bag",
    "drab indigo" to "4 dotted magenta bags, 3 drab lavender bags, 4 dotted lime bags, 5 wavy aqua bags",
    "faded black" to "4 plaid gold bags",
    "muted violet" to "2 drab aqua bags, 2 light crimson bags, 2 posh tomato bags",
    "posh orange" to "3 shiny salmon bags",
    "bright gray" to "1 mirrored gray bag, 3 mirrored magenta bags, 1 clear salmon bag",
    "plaid plum" to "3 striped magenta bags, 1 drab fuchsia bag",
    "posh black" to "5 dotted orange bags, 2 muted beige bags",
    "striped maroon" to "5 clear gold bags, 5 clear tomato bags, 4 muted cyan bags, 1 pale coral bag",
    "dim indigo" to "1 shiny lavender bag, 2 posh blue bags, 3 drab silver bags",
    "clear magenta" to "3 dark magenta bags, 2 drab gold bags, 4 dull white bags, 5 light maroon bags",
    "plaid red" to "4 drab violet bags, 4 vibrant brown bags",
    "light gray" to "no other bags",
    "clear red" to "3 drab purple bags, 2 pale magenta bags, 2 bright violet bags",
    "pale coral" to "5 muted chartreuse bags, 4 plaid olive bags",
    "dull red" to "4 drab lavender bags, 5 bright orange bags, 5 dull white bags",
    "clear lavender" to "4 wavy brown bags, 1 faded bronze bag",
    "dim beige" to "3 dotted tomato bags, 4 bright magenta bags",
    "striped orange" to "4 vibrant lime bags, 1 vibrant tomato bag, 1 faded plum bag",
    "drab beige" to "1 light lime bag, 1 shiny lavender bag, 2 striped tomato bags, 1 dim orange bag",
    "mirrored tomato" to "2 posh bronze bags",
    "mirrored violet" to "3 dotted lime bags, 2 dotted teal bags",
    "muted silver" to "1 bright salmon bag, 3 shiny crimson bags, 1 dim tomato bag",
    "clear gold" to "1 dark violet bag",
    "faded beige" to "1 dull fuchsia bag, 4 shiny yellow bags",
    "mirrored red" to "5 wavy lavender bags, 2 wavy silver bags",
    "wavy coral" to "4 drab yellow bags",
    "shiny yellow" to "1 shiny lavender bag, 5 drab silver bags, 4 drab gold bags",
    "shiny chartreuse" to "5 faded brown bags",
    "light black" to "1 plaid cyan bag, 5 dark chartreuse bags, 5 muted bronze bags",
    "bright blue" to "3 drab silver bags, 5 dim orange bags",
    "mirrored gray" to "4 pale indigo bags",
    "shiny gold" to "1 dim lavender bag, 5 mirrored gray bags, 1 light maroon bag",
    "faded plum" to "2 shiny orange bags, 1 pale plum bag, 2 posh coral bags, 3 shiny white bags",
    "dotted olive" to "1 drab aqua bag, 4 posh black bags, 3 pale salmon bags, 2 dotted yellow bags",
    "vibrant tomato" to "3 muted brown bags, 4 faded teal bags, 4 dotted brown bags",
    "vibrant yellow" to "1 drab coral bag, 3 dark purple bags, 1 wavy crimson bag",
    "muted coral" to "1 dark plum bag, 3 wavy blue bags, 3 bright yellow bags, 4 dark maroon bags",
    "dark white" to "1 dim brown bag, 2 drab gray bags, 3 clear cyan bags",
    "light salmon" to "4 dim violet bags, 2 shiny gold bags, 5 pale turquoise bags",
    "dark green" to "1 pale yellow bag, 5 shiny gold bags",
    "dark lime" to "2 plaid red bags, 4 dotted tomato bags, 4 posh bronze bags",
    "light tan" to "5 light coral bags",
    "striped gold" to "3 vibrant maroon bags, 4 clear lime bags",
    "dotted silver" to "3 striped aqua bags, 2 mirrored aqua bags, 1 vibrant brown bag",
    "dull aqua" to "4 pale gray bags, 4 mirrored cyan bags, 2 shiny turquoise bags, 5 striped crimson bags",
    "shiny plum" to "2 plaid green bags, 3 light crimson bags",
    "faded indigo" to "5 light tomato bags, 3 pale indigo bags, 1 shiny magenta bag, 5 muted tomato bags",
    "striped blue" to "2 shiny crimson bags, 3 wavy crimson bags, 4 dotted red bags",
    "muted salmon" to "1 faded red bag, 1 dim gray bag, 2 dotted gray bags",
    "pale aqua" to "5 clear magenta bags, 3 dim beige bags",
    "pale plum" to "5 bright indigo bags, 2 light crimson bags, 1 muted white bag",
    "pale green" to "5 bright aqua bags, 1 dull fuchsia bag",
    "wavy tan" to "2 posh tomato bags",
    "wavy teal" to "2 mirrored violet bags",
    "dim maroon" to "3 drab fuchsia bags",
    "bright silver" to "5 dull black bags",
    "plaid magenta" to "2 muted olive bags, 5 mirrored plum bags, 1 posh lavender bag",
    "wavy lavender" to "3 pale salmon bags, 4 wavy green bags, 5 posh yellow bags",
    "striped olive" to "2 pale fuchsia bags, 1 pale silver bag, 4 dull brown bags, 4 dim blue bags",
    "shiny cyan" to "2 light tomato bags, 2 faded indigo bags, 3 drab lime bags",
    "bright white" to "4 dark orange bags",
    "mirrored lavender" to "3 drab gold bags, 4 mirrored white bags, 4 bright orange bags, 1 pale gray bag",
    "dark brown" to "1 dark chartreuse bag, 2 muted bronze bags, 3 bright magenta bags, 5 striped chartreuse bags",
    "dark blue" to "5 vibrant brown bags, 4 drab maroon bags, 5 wavy brown bags, 3 drab silver bags",
    "bright gold" to "5 dark silver bags",
    "dotted gray" to "1 posh bronze bag, 5 drab fuchsia bags, 3 mirrored gray bags, 1 clear cyan bag",
    "clear teal" to "1 dim beige bag",
    "drab yellow" to "3 bright blue bags",
    "bright purple" to "2 posh lavender bags",
    "shiny bronze" to "1 faded red bag",
    "dark black" to "2 mirrored beige bags, 3 wavy silver bags",
    "mirrored coral" to "3 drab beige bags, 3 wavy silver bags, 4 dim lavender bags, 4 drab silver bags",
    "dim white" to "4 posh bronze bags",
    "dim brown" to "1 muted bronze bag, 2 drab gold bags, 4 striped tomato bags, 5 drab silver bags",
    "striped white" to "1 dotted crimson bag, 4 pale indigo bags, 2 dark chartreuse bags, 1 dotted brown bag",
    "dark coral" to "2 dark brown bags, 4 mirrored plum bags, 4 bright tan bags, 5 posh blue bags",
    "faded bronze" to "4 drab fuchsia bags, 1 plaid yellow bag",
    "dim fuchsia" to "3 plaid yellow bags, 1 wavy coral bag, 2 dotted blue bags",
    "mirrored blue" to "5 dull crimson bags, 1 pale chartreuse bag, 3 vibrant plum bags",
    "wavy plum" to "1 pale olive bag, 1 bright red bag, 3 clear tan bags, 2 drab gray bags",
    "plaid bronze" to "5 wavy silver bags, 4 bright magenta bags, 1 dim orange bag",
    "dotted tomato" to "1 vibrant brown bag, 5 mirrored gray bags",
    "dim yellow" to "1 vibrant teal bag, 5 plaid white bags",
    "faded olive" to "4 wavy beige bags",
    "bright coral" to "2 muted maroon bags, 2 posh indigo bags",
    "mirrored aqua" to "1 light gray bag",
    "faded blue" to "1 vibrant tomato bag, 1 mirrored salmon bag",
    "mirrored fuchsia" to "5 plaid beige bags, 5 clear violet bags",
    "bright orange" to "3 dull turquoise bags, 3 striped blue bags, 3 posh maroon bags, 5 dotted brown bags",
    "drab white" to "5 drab maroon bags, 3 shiny coral bags, 1 drab gray bag",
    "plaid blue" to "5 light turquoise bags, 4 dark violet bags, 1 bright indigo bag, 3 dull fuchsia bags",
    "bright tomato" to "4 vibrant tomato bags, 1 dull purple bag, 4 clear tomato bags, 2 dotted yellow bags",
    "dark gray" to "3 light green bags, 3 dull teal bags, 2 wavy chartreuse bags, 1 vibrant coral bag",
    "light lime" to "no other bags",
    "dim magenta" to "2 light gold bags, 4 dotted teal bags, 3 dull crimson bags",
    "vibrant cyan" to "2 dark brown bags, 1 dim crimson bag",
    "dotted salmon" to "2 shiny magenta bags, 4 dark orange bags, 3 striped lavender bags, 3 mirrored violet bags",
    "plaid chartreuse" to "3 dull crimson bags, 1 dull red bag, 4 posh white bags, 5 bright indigo bags",
    "muted plum" to "1 clear salmon bag, 3 mirrored lime bags",
    "dark bronze" to "4 clear chartreuse bags",
    "dim blue" to "4 light yellow bags, 5 mirrored beige bags",
    "vibrant gold" to "4 muted bronze bags, 4 plaid gold bags",
    "drab gray" to "1 dark chartreuse bag",
    "dotted lime" to "1 dotted indigo bag, 4 dull gray bags, 3 drab gray bags, 4 shiny bronze bags",
    "mirrored orange" to "5 mirrored tan bags",
    "dark lavender" to "3 dim chartreuse bags, 4 posh black bags, 1 clear beige bag",
    "muted lime" to "1 vibrant violet bag",
    "dull indigo" to "3 faded indigo bags, 5 bright orange bags, 4 posh turquoise bags, 1 dim gray bag",
    "pale magenta" to "5 dotted gray bags, 3 drab silver bags, 2 wavy salmon bags",
    "plaid lavender" to "5 vibrant tomato bags",
    "clear bronze" to "3 shiny crimson bags",
    "bright salmon" to "5 mirrored bronze bags, 2 clear black bags, 4 plaid green bags, 5 faded red bags",
    "wavy indigo" to "3 shiny lavender bags, 3 vibrant brown bags, 2 dotted beige bags, 4 wavy brown bags",
    "light maroon" to "3 light black bags, 3 plaid maroon bags, 2 wavy silver bags, 5 vibrant brown bags",
    "muted gold" to "5 posh black bags",
    "dull lavender" to "3 plaid beige bags, 4 clear cyan bags, 5 striped aqua bags, 4 dotted gray bags",
    "muted brown" to "1 faded olive bag, 2 drab gray bags, 5 wavy salmon bags",
    "dotted orange" to "2 dotted red bags",
    "dim plum" to "5 drab lime bags, 1 plaid tan bag",
    "muted orange" to "3 plaid green bags",
    "dull chartreuse" to "4 dark maroon bags, 5 vibrant tan bags, 1 mirrored coral bag, 5 dull lime bags",
    "striped gray" to "2 vibrant crimson bags",
    "posh gray" to "3 dark orange bags",
    "shiny lime" to "4 muted yellow bags, 2 wavy cyan bags",
    "dull lime" to "1 drab purple bag",
    "striped bronze" to "2 dim white bags, 1 dim coral bag, 3 light maroon bags, 5 dim blue bags",
    "wavy orange" to "2 pale blue bags, 3 muted violet bags",
    "pale brown" to "3 wavy indigo bags, 1 bright green bag",
    "dull silver" to "5 wavy aqua bags, 5 shiny maroon bags, 5 dotted chartreuse bags",
    "bright red" to "2 dark gold bags, 5 dark tan bags",
    "dotted brown" to "1 striped turquoise bag",
    "plaid crimson" to "3 posh white bags, 4 pale plum bags, 3 dark orange bags, 3 shiny magenta bags",
    "dotted plum" to "5 posh blue bags, 5 dark indigo bags, 5 wavy silver bags",
    "light tomato" to "3 light purple bags, 5 clear plum bags",
    "dull bronze" to "3 clear magenta bags, 1 faded tan bag",
    "drab turquoise" to "2 posh lavender bags, 2 faded tomato bags, 5 mirrored tomato bags",
    "striped lavender" to "2 dotted turquoise bags, 5 plaid indigo bags",
    "pale violet" to "5 light red bags, 1 striped chartreuse bag, 1 drab chartreuse bag, 1 bright silver bag",
    "posh gold" to "2 bright blue bags",
    "dull maroon" to "4 dotted teal bags, 2 faded silver bags, 3 posh gray bags",
    "shiny beige" to "3 light orange bags, 4 drab fuchsia bags, 3 muted beige bags",
    "dim silver" to "1 dotted gold bag",
    "pale orange" to "5 dotted orange bags, 3 dim white bags",
    "wavy aqua" to "5 vibrant purple bags",
    "posh salmon" to "2 drab red bags",
    "clear tan" to "4 bright plum bags, 4 faded fuchsia bags, 1 mirrored crimson bag, 1 faded salmon bag",
    "clear orange" to "1 drab aqua bag",
    "posh violet" to "2 vibrant magenta bags, 3 mirrored plum bags, 5 light orange bags",
    "dull crimson" to "5 faded violet bags, 3 dim indigo bags, 2 light red bags, 2 clear red bags",
    "mirrored teal" to "1 drab teal bag",
    "drab violet" to "2 mirrored plum bags, 4 drab red bags",
    "shiny violet" to "5 shiny aqua bags, 1 striped brown bag, 1 dark blue bag, 5 wavy white bags",
)
